error: Error capturado en el errorHandler:  getAllPets no encontro mascotas en la base de datos {"stack":"Error: getAllPets no encontro mascotas en la base de datos\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:11:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-30T13:23:45.358Z"}
error: Error capturado en el errorHandler:  Pets validation failed: birthDate: Cast to date failed for value "formato no valido seguramente" (type string) at path "birthDate" {"_message":"Pets validation failed","errors":{"birthDate":{"kind":"date","message":"Cast to date failed for value \"formato no valido seguramente\" (type string) at path \"birthDate\"","name":"CastError","path":"birthDate","reason":{"actual":false,"code":"ERR_ASSERTION","expected":true,"generatedMessage":true,"operator":"=="},"stringValue":"\"formato no valido seguramente\"","value":"formato no valido seguramente","valueType":"string"}},"stack":"ValidationError: Pets validation failed: birthDate: Cast to date failed for value \"formato no valido seguramente\" (type string) at path \"birthDate\"\n    at Document.invalidate (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\document.js:3123:32)\n    at model.$set (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\document.js:1463:12)\n    at model.$set (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\document.js:1146:16)\n    at model.Document (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\document.js:166:12)\n    at model.Model (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:121:12)\n    at new model (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:5038:15)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:3187:22\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:3222:7\n    at Array.forEach (<anonymous>)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:3221:15","timestamp":"2025-05-30T13:31:36.921Z"}
error: Error capturado en el errorHandler:  INVALID_PARAM {"stack":"Error: INVALID_PARAM\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:26:19)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:47:12)","timestamp":"2025-05-30T13:35:41.140Z"}
error: Error capturado en el errorHandler:  Unexpected token ',', ..."  "name": ,
    "sp"... is not valid JSON {"body":"{\r\n    \"name\": ,\r\n    \"specie\": \"mezcla de collie con bestia\",\r\n    \"birthDate\": \"1990-05-30\"\r\n}","expose":true,"stack":"SyntaxError: Unexpected token ',', ...\"  \"name\": ,\r\n    \"sp\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at invokeCallback (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":400,"statusCode":400,"timestamp":"2025-05-30T13:36:10.933Z","type":"entity.parse.failed"}
error: Error capturado en el errorHandler:  Expected ',' or '}' after property value in JSON at position 29 {"body":"{\r\n    \"name\": \r\n    \"specie\": \"mezcla de collie con bestia\",\r\n    \"birthDate\": \"1990-05-30\"\r\n}","expose":true,"stack":"SyntaxError: Expected ',' or '}' after property value in JSON at position 29\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at invokeCallback (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":400,"statusCode":400,"timestamp":"2025-05-30T13:36:26.197Z","type":"entity.parse.failed"}
error: Error capturado en el errorHandler:  Unexpected token 'i', ..."  "name": ipa,
    "... is not valid JSON {"body":"{\r\n    \"name\": ipa,\r\n    \"specie\": \"mezcla de collie con bestia\",\r\n    \"birthDate\": \"1990-05-30\"\r\n}","expose":true,"stack":"SyntaxError: Unexpected token 'i', ...\"  \"name\": ipa,\r\n    \"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at invokeCallback (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":400,"statusCode":400,"timestamp":"2025-05-30T13:36:35.858Z","type":"entity.parse.failed"}
error: Error capturado en el errorHandler:  INVALID_PARAM {"stack":"Error: INVALID_PARAM\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:48:19)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-05-30T22:37:04.277Z"}
error: Error capturado en el errorHandler:  INVALID_PARAM {"stack":"Error: INVALID_PARAM\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:48:19)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-05-30T22:37:58.346Z"}
error: Error capturado en updatePet:  INVALID_PARAM {"stack":"Error: INVALID_PARAM\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:48:19)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-05-30T22:43:52.603Z"}
error: Error capturado en el errorHandler:  INVALID_PARAM {"stack":"Error: INVALID_PARAM\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:48:19)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-05-30T22:43:52.605Z"}
error: Error capturado en deletePet {"timestamp":"2025-05-30T22:51:20.157Z"}
error: Error capturado en el errorHandler:  No se pudo eliminar el documento por que no existe {"stack":"Error: No se pudo eliminar el documento por que no existe\n    at deletePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:71:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-30T22:51:20.160Z"}
error: Error capturado en deletePet {"timestamp":"2025-05-30T22:52:54.506Z"}
error: Error capturado en el errorHandler:  No se pudo eliminar el documento por que no existe {"stack":"Error: No se pudo eliminar el documento por que no existe\n    at deletePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:69:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-30T22:52:54.507Z"}
error: Error capturado en el errorHandler:  Error en la obtencion de documentos {"cause":"No se obtuvieron los documentos de la base de datos","code":400,"custom":true,"name":"getError","stack":"getError: Error en la obtencion de documentos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:14:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-01T00:04:42.502Z"}
error: Error capturado en el errorHandler:  Error en la obtencion de documentos {"cause":"No se obtuvieron los documentos de la base de datos","code":400,"custom":true,"name":"getError","stack":"getError: Error en la obtencion de documentos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:14:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-01T00:21:35.747Z"}
error: Error capturado en el errorHandler:  Error en la obtencion de documentos {"cause":"No se obtuvieron los documentos de la base de datos","code":400,"custom":true,"name":"getError","stack":"getError: Error en la obtencion de documentos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:14:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-01T00:23:29.488Z"}
error: Error capturado en el errorHandler:  Error en la obtencion de documentos {"cause":"No se obtuvieron los documentos de la base de datos","code":400,"custom":true,"name":"getError","stack":"getError: Error en la obtencion de documentos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:14:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-01T00:27:09.955Z"}
error: Error capturado en el errorHandler:  Error en la obtencion de documentos {"cause":"No se obtuvieron los documentos de la base de datos","code":400,"custom":true,"name":"getError","stack":"getError: Error en la obtencion de documentos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:14:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-01T00:27:18.696Z"}
error: Error capturado en el errorHandler:  Error en la obtencion de documentos {"cause":"No se obtuvieron los documentos de la base de datos","code":400,"custom":true,"name":"getError","stack":"getError: Error en la obtencion de documentos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:14:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-01T00:29:36.095Z"}
error: Error capturado en el errorHandler:  Error forzado en el DAO de pet {"stack":"Error: Error forzado en el DAO de pet\n    at Pet.get (file:///C:/Users/Asus/Desktop/ADOPTME/src/dao/Pets.dao.js:6:15)\n    at PetRepository.getAll (file:///C:/Users/Asus/Desktop/ADOPTME/src/repository/GenericRepository.js:8:25)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:11:40)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-06-01T00:30:10.534Z"}
error: Error capturado en el errorHandler:  Error forzado en el DAO de pet {"stack":"Error: Error forzado en el DAO de pet\n    at Pet.get (file:///C:/Users/Asus/Desktop/ADOPTME/src/dao/Pets.dao.js:6:15)\n    at PetRepository.getAll (file:///C:/Users/Asus/Desktop/ADOPTME/src/repository/GenericRepository.js:8:25)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:11:40)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-06-01T00:31:44.487Z"}
error: Error capturado en el errorHandler:  Debes pasar correctamente los datos para crear la mascota {"cause":"Los parametros recibidos en el req.body son invalidos o estan incompletos","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: Debes pasar correctamente los datos para crear la mascota\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:27:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-01T00:41:04.344Z"}
error: Error capturado en el errorHandler:  Debes pasar correctamente los datos para crear la mascota {"cause":"Los parametros recibidos en el req.body son invalidos o estan incompletos","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: Debes pasar correctamente los datos para crear la mascota\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:27:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-01T00:42:21.261Z"}
error: Error capturado en el errorHandler:  Debes pasar correctamente los datos para crear la mascota {"cause":"Los parametros recibidos en el req.body son invalidos o estan incompletos","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: Debes pasar correctamente los datos para crear la mascota\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:27:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-01T00:43:57.816Z"}
error: Error capturado en el errorHandler:  Error en la obtencion de documentos {"cause":"No se obtuvieron los documentos de la base de datos","code":404,"custom":true,"name":"getError","stack":"getError: Error en la obtencion de documentos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:13:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-01T00:44:34.703Z"}
error: Error capturado en el errorHandler:  El tipo de dato de los campos ingresados no es de tipo String como deberia ser {"cause":"Los datos ingresados no con String","code":400,"custom":true,"name":"DATA_INVALID","stack":"DATA_INVALID: El tipo de dato de los campos ingresados no es de tipo String como deberia ser\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:36:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-01T15:46:37.542Z"}
error: Error capturado en el errorHandler:  El tipo de dato de los campos ingresados no es de tipo String como deberia ser {"cause":"Los datos ingresados no con String","code":400,"custom":true,"name":"DATA_INVALID","stack":"DATA_INVALID: El tipo de dato de los campos ingresados no es de tipo String como deberia ser\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:36:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-01T15:55:36.060Z"}
error: Error capturado en el errorHandler:  La fecha ingresada en el campo birthDate es invalida {"cause":"Fecha invalida","code":400,"custom":true,"name":"DATA_INVALID","stack":"DATA_INVALID: La fecha ingresada en el campo birthDate es invalida\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:39:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-01T15:59:06.889Z"}
error: Error capturado en el errorHandler:  La fecha ingresada en el campo birthDate es invalida {"cause":"Fecha invalida","code":400,"custom":true,"name":"DATA_INVALID","stack":"DATA_INVALID: La fecha ingresada en el campo birthDate es invalida\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:35:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-01T16:01:38.321Z"}
error: Error capturado en el errorHandler:  Error forzado en el DAO de pet {"stack":"Error: Error forzado en el DAO de pet\n    at Pet.save (file:///C:/Users/Asus/Desktop/ADOPTME/src/dao/Pets.dao.js:15:15)\n    at PetRepository.create (file:///C:/Users/Asus/Desktop/ADOPTME/src/repository/GenericRepository.js:16:25)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:38:42)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)","timestamp":"2025-06-01T16:05:06.305Z"}
error: Error capturado en el errorHandler:  Debes pasar correctamente los datos para crear la mascota {"cause":"Los parametros recibidos en el req.body son invalidos o estan incompletos","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: Debes pasar correctamente los datos para crear la mascota\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:29:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-01T16:19:00.892Z"}
error: Error capturado en updatePet:  El id ingresado es invalido {"cause":"No es del typeof object","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: El id ingresado es invalido\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:61:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)","timestamp":"2025-06-01T16:36:12.448Z"}
error: Error capturado en el errorHandler:  El id ingresado es invalido {"cause":"No es del typeof object","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: El id ingresado es invalido\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:61:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)","timestamp":"2025-06-01T16:36:12.453Z"}
error: Error capturado en updatePet:  El id ingresado es invalido {"cause":"No es del typeof object","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: El id ingresado es invalido\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:61:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)","timestamp":"2025-06-01T16:36:26.750Z"}
error: Error capturado en el errorHandler:  El id ingresado es invalido {"cause":"No es del typeof object","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: El id ingresado es invalido\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:61:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)","timestamp":"2025-06-01T16:36:26.754Z"}
error: Error capturado en updatePet:  Cast to date failed for value "2024-01-2024" (type string) at path "birthDate" {"kind":"date","path":"birthDate","reason":{"actual":false,"code":"ERR_ASSERTION","expected":true,"generatedMessage":true,"operator":"=="},"stack":"CastError: Cast to date failed for value \"2024-01-2024\" (type string) at path \"birthDate\"\n    at model.Query.exec (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\query.js:4897:21)\n    at Query.then (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\query.js:4996:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","stringValue":"\"2024-01-2024\"","timestamp":"2025-06-01T16:37:00.364Z","value":"2024-01-2024","valueType":"string"}
error: Error capturado en el errorHandler:  Cast to date failed for value "2024-01-2024" (type string) at path "birthDate" {"kind":"date","path":"birthDate","reason":{"actual":false,"code":"ERR_ASSERTION","expected":true,"generatedMessage":true,"operator":"=="},"stack":"CastError: Cast to date failed for value \"2024-01-2024\" (type string) at path \"birthDate\"\n    at model.Query.exec (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\query.js:4897:21)\n    at Query.then (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\query.js:4996:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","stringValue":"\"2024-01-2024\"","timestamp":"2025-06-01T16:37:00.371Z","value":"2024-01-2024","valueType":"string"}
error: Error capturado en updatePet:  Informacion para editar la mascota incompleta {"cause":"Faltan campos por completar","code":400,"custom":true,"name":"updateError","stack":"updateError: Informacion para editar la mascota incompleta\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:65:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)","timestamp":"2025-06-01T16:37:43.726Z"}
error: Error capturado en el errorHandler:  Informacion para editar la mascota incompleta {"cause":"Faltan campos por completar","code":400,"custom":true,"name":"updateError","stack":"updateError: Informacion para editar la mascota incompleta\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:65:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)","timestamp":"2025-06-01T16:37:43.727Z"}
error: Error capturado en updatePet:  Informacion para editar la mascota incompleta {"cause":"Faltan campos por completar","code":400,"custom":true,"name":"updateError","stack":"updateError: Informacion para editar la mascota incompleta\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:61:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)","timestamp":"2025-06-01T16:39:29.449Z"}
error: Error capturado en el errorHandler:  Informacion para editar la mascota incompleta {"cause":"Faltan campos por completar","code":400,"custom":true,"name":"updateError","stack":"updateError: Informacion para editar la mascota incompleta\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updatePet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:61:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:365:14)\n    at param (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:376:14)\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:421:3)","timestamp":"2025-06-01T16:39:29.453Z"}
error: Error capturado en getAllUsers {"timestamp":"2025-06-02T12:22:56.073Z"}
error: Error capturado en el errorHandler:  No hay usuarios guadados en la base de datos {"cause":"Coleccion de usuarios vacia","code":404,"custom":true,"name":"getError","stack":"getError: No hay usuarios guadados en la base de datos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at getAllUsers (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/users.controller.js:12:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T12:22:56.077Z"}
error: Error capturado en updateUser Error forzado {"stack":"Error: Error forzado\n    at Users.update (file:///C:/Users/Asus/Desktop/ADOPTME/src/dao/Users.dao.js:19:15)\n    at UserRepository.update (file:///C:/Users/Asus/Desktop/ADOPTME/src/repository/GenericRepository.js:20:25)\n    at updateUser (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/users.controller.js:63:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T13:15:47.727Z"}
error: Error capturado en el errorHandler:  Error forzado {"stack":"Error: Error forzado\n    at Users.update (file:///C:/Users/Asus/Desktop/ADOPTME/src/dao/Users.dao.js:19:15)\n    at UserRepository.update (file:///C:/Users/Asus/Desktop/ADOPTME/src/repository/GenericRepository.js:20:25)\n    at updateUser (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/users.controller.js:63:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T13:15:47.731Z"}
error: Error capturado en updateUser Usuario no encontrado {"cause":"No hay usuario con id 683da37e3101344934d5780b almacenado en la base de datos","code":404,"custom":true,"name":"getError","stack":"getError: Usuario no encontrado\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updateUser (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/users.controller.js:61:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T13:17:06.405Z"}
error: Error capturado en el errorHandler:  Usuario no encontrado {"cause":"No hay usuario con id 683da37e3101344934d5780b almacenado en la base de datos","code":404,"custom":true,"name":"getError","stack":"getError: Usuario no encontrado\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at updateUser (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/users.controller.js:61:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T13:17:06.408Z"}
error: Error capturado en deleteUser:  No se pudo eliminar al usuario {"cause":"El usuario no se encontraba registrado en la base de datos","code":404,"custom":true,"name":"deleteError","stack":"deleteError: No se pudo eliminar al usuario\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at deleteUser (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/users.controller.js:82:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T15:42:04.548Z"}
error: Error capturado en el errorHandler:  No se pudo eliminar al usuario {"cause":"El usuario no se encontraba registrado en la base de datos","code":404,"custom":true,"name":"deleteError","stack":"deleteError: No se pudo eliminar al usuario\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at deleteUser (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/users.controller.js:82:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T15:42:04.561Z"}
error: Error capturado en register:  Se deben completar todos los campos {"cause":"Campos incompletos","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: Se deben completar todos los campos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at register (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/sessions.controller.js:15:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-02T16:15:54.659Z"}
error: Error capturado en el errorHandler:  Se deben completar todos los campos {"cause":"Campos incompletos","code":400,"custom":true,"name":"INVALID_PARAMS","stack":"INVALID_PARAMS: Se deben completar todos los campos\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at register (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/sessions.controller.js:15:25)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-02T16:15:54.661Z"}
error: Error capturado en register:  El correo electronico ya se encuentra en uso {"cause":"Dato repetido","code":400,"custom":true,"name":"repeateadData","stack":"repeateadData: El correo electronico ya se encuentra en uso\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at register (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/sessions.controller.js:23:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T16:16:18.148Z"}
error: Error capturado en el errorHandler:  El correo electronico ya se encuentra en uso {"cause":"Dato repetido","code":400,"custom":true,"name":"repeateadData","stack":"repeateadData: El correo electronico ya se encuentra en uso\n    at CustomError.generateError (file:///C:/Users/Asus/Desktop/ADOPTME/src/utils/CustomError.js:3:21)\n    at register (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/sessions.controller.js:23:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-06-02T16:16:18.148Z"}
